### PR TITLE
Update sonar scanner version to latest 4.2.0.1873

### PR DESCRIPTION
**Pull request by adriengibrat**

### CODE REVIEW

**Comment by mercuriete** [comment]
Thanks for the contribution.
Tomorrow i Will test It.

**Comment by mercuriete** [comment]
I didnt test it but I will merge it anyways

**Comment by mercuriete** [comment]
@adriengibrat thanks for your contribution!!!!

**Comment by adriengibrat** [comment]
I did test ;) You'r welcome.

Could you release the version to DockerHub ?

**Comment by mercuriete** [comment]
yes of course It is already done.
It is:
https://hub.docker.com/r/mercuriete/sonar-scanner/tags
```
latest
4.2.0.1873
```

for onbuild:
```
onbuild
4.2.0.1873-onbuild
```

**Comment by mercuriete** [comment]
@adriengibrat 

The example is updated as well
https://github.com/mercuriete/docker-sonar-scanner-example

**Pull request merged**
